danielfrg/mkdocs-jupyter

.github/workflows/pythonpackage.yml, tests/docs/demo.ipynb, tests/docs/index.md, tests/mkdocs-basic.yml, tests/mkdocs-jupyter.yml, tests/test_base_usage.py
This pull request adds unit tests that demonstrates that [this issue](https://github.com/danielfrg/mkdocs-jupyter/issues/3) depends on the version of mkdocs. There was an update last month that breaks this package. I did not see an easy fix, but I figure the least I could at least add unit tests to make the issue reproducible.
=> pytest checks

README.md, mkdocs_jupyter/convert.py, mkdocs_jupyter/plugin.py
Fix https://github.com/danielfrg/mkdocs-jupyter/issues/19
It was quite simple to integrate it.
That being said I don't think I'll use that option since the main goal was to embed a custom ipywidget library called [nglview](https://github.com/nglviewer/nglview) but I can't make the JS widget to appear on the generated HTML. I tried tweaking the template without success.
Anyway, that kernel_name option should still be useful.
=> Add kernel_name option

README.md
@danielfrg I noticed the right sidebar toc only works if we follow a hierarchical header structure and avoid using h1. I have added a section in the docs to reflect this.
=> updating readme with toc section

mkdocs_jupyter/convert.py
Accents (é, à) in anchor links were not rendered properly. I found that moving slugify fix the problem.  
I also think that the id and the ref should be the same, hence applying slugify to both.
=> Fix accent problems in anchor link

mkdocs_jupyter/nbconvert2.py
When using notebooks with non-ASCII characters I would get an error (pasted below) about Unicode decoding.
In this pull request I simply set default encoding to "utf-8" when doing the json.load().
```
(base) PS C:\g\blog> mkdocs serve
INFO     -  Building documentation...
ERROR    -  Config value: 'plugins'. Error: Invalid Plugins configuration. Expected a list or dict.
Aborted with 1 Configuration Errors!
(base) PS C:\g\blog> mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  Converting notebook (execute=False): C:\g\blog\docs\test.ipynb
ERROR    -  Error reading page 'test.ipynb': 'charmap' codec can't decode byte 0x90 in position 666: character maps to
<undefined>
Traceback (most recent call last):
File …
```
=> set notebook encoding to utf-8

README.md, mkdocs_jupyter/plugin.py
I just realized this is sort of redundant with [mkdocs-exclude](https://github.com/apenwarr/mkdocs-exclude), but figured I would open anyway since it would help avoid installing multiple plugins.
=> Add ability to define patterns of files to include/ignore

mkdocs_jupyter/convert.py
closes #69 
Because `mkdocs-jupyter` require >py3.7, I don't think `ipython_genutils` is needed anymore.
=> remove ipython_genutils code

README.md, mkdocs_jupyter/nbconvert2.py, mkdocs_jupyter/plugin.py
=> Added show_input and no_input settings

pyproject.toml
This PR changes the mkdocs version lower bound from `1.4.2` to `1.4.0` as discussed in #134
=> Change mkdocs version lower bound

mkdocs_jupyter/convert.py
See changelog entry for `0.7.0rc2` of https://pypi.org/project/defusedxml
This use was giving me deprecation warnings
=> Update use of deprecated `defusedxml.cElementTree`

src/mkdocs_jupyter/plugin.py
"tests" will not be part of the package in the next releases of MkDocs
=> Avoid using an import from "mkdocs.tests."

.github/workflows/test.yml, pyproject.toml, requirements-dev.lock, requirements.lock
This PR aims to add back the support python 3.8.
The estimated EoL for python 3.8 is `2024-10`, https://devguide.python.org/versions/
=> chore: Add back support to py38

src/mkdocs_jupyter/templates/mkdocs_html/notebook.html.j2
Thank you for working on the amazing project!
This pull request modifies the footer block in the `notebook.html.j2` template to include widget states in the exported HTML, which I found required to embed Jupyter Widgets in the HTML properly. (`include_requirejs` must be enabled as well.)
The code is just a port from the original `base.html.j2` of `nbconvert`: https://github.com/jupyter/nbconvert/blob/89de373448477b963729fe62a43bbc4bcffcdad9/share/templates/lab/base.html.j2#L323-L331
=> Include widget states in `notebook.html.j2`

src/mkdocs_jupyter/nbconvert2.py, src/mkdocs_jupyter/tests/mkdocs/docs/backquote_toc_test.ipynb, src/mkdocs_jupyter/tests/test_toc.py
I recently started to use "mkdocs" with "mkdocs-jupyter" package for my notebooks and stumbled across an issue, when I used C++ code samples under backquotes.
Basically if there's a line starting with number sign (#) within 1-3 backquotes (`), which is allowed in markdown, table of contents stops before first encounter of this.
For example, before changes, this IPython Notebook:
resulting in this page (look at the table of contents on the right)
After changes:
- I also added tests (see [test_toc.py](src/mkdocs_jupyter/tests/test_toc.py))
Sadly I couldn't successfully run the other tests (regardless of any changes), but I set up project _via rye_ as described in [CONTRIBUTING.md](https://github.com/danielfrg/mkdocs-jupyter/blob/main/CONTRIBUTING.md)
=> Fix of possible issue with Table of Contents when leaving code under backquotes in markdown

demo/mkdocs.yml, src/mkdocs_jupyter/nbconvert2.py, src/mkdocs_jupyter/plugin.py
Added the option to define a custom mathjax URL.  
Not sure if all the modifications are really necessary in the code, please check!
It also works with the privacy plugin of mkdocs-material.
Off topic: I'm not able to run the demo, some templates are missing in this repo. If I install mkdocs-jupyter via Pypi, the required template files are present.
=> added custom_mathjax_url option

demo/docs/variational-inference-nb.ipynb, src/mkdocs_jupyter/nbconvert2.py, src/mkdocs_jupyter/plugin.py, src/mkdocs_jupyter/tests/mkdocs/base-with-mds.yml, src/mkdocs_jupyter/tests/mkdocs/docs/demo-jupytext.md, src/mkdocs_jupyter/tests/mkdocs/docs/variational-inference.ipynb, src/mkdocs_jupyter/tests/mkdocs/docs/variational-inference.md, src/mkdocs_jupyter/tests/mkdocs/material-with-mds.yml, src/mkdocs_jupyter/tests/test_base_usage.py
closes #215.
@danielfrg, here is a simple implementation supporting markdown files.  As mentioned in #215, the biggest question for me is how best to cleanly add support for markdown files with jupytext frontmatter without causing any issues with "regular" markdown files that don't represent notebooks.
let me know if you have any thoughts
also, if you'd rather not check those two duplicated files for tests, we can probably create them as fixtures using jupytext to convert one of the other files
=> feat: execute markdown with jupytext frontmatter

.github/workflows/test.yml, CHANGELOG.md, src/mkdocs_jupyter/plugin.py
This PR fixes the following issue(s):
Instead of blindly copying all source files, including plain markdown files, only copy files converted by the plugin. This prevents all plain markdown files from being copied into the build output.
I also replaced the print statements with logging statements. Otherwise, the print can easily mess up automated scripts.
=> Only copy source files if they are converted by the plugin

src/mkdocs_jupyter/plugin.py
Reintroduce `custom_mathjax_url` plugin arg as per issue https://github.com/danielfrg/mkdocs-jupyter/issues/223.
=> Reintroduce `custom_mathjax_url` plugin arg

demo/mkdocs.yml
On the demo site i kept trying to get back to github but ending up in the wrong spot.
=> Use correct repo URL

src/mkdocs_jupyter/plugin.py, src/mkdocs_jupyter/tests/test_pkg.py
Closes #239 by changing the order of checks in `should_include` to return early when files match ignored patterns. For Markdown files, this can avoid unnecessary reads and potential warnings from `jupytext`.
I wasn't sure the best place to put the test, so I just included it alongside some other API tests for now. Happy to move that elsewhere.
=> Check ignore patterns before reading files

src/mkdocs_jupyter/nbconvert2.py
Hi, thanks for maintaining this!
We noticed that some of the "copy" buttons in our converted notebooks ([example](https://vespa-engine.github.io/pyvespa/examples/video_search_twelvelabs_cloud.html)) failed to include parts of the code that are contained in angle brackets < >:
when copying
`type="array<float>",`
what I get in my clipboard is just
`type="array",`
HTML escaping the source fixes this.
=> html escape source text for clipboard copy
